spring:
  application:
    name: learning-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
#    root: INFO
    org.springframework.web: INFO
    com.arake.learningapp: DEBUG